export interface Movie {
  id: string;
  title: string;
  genre: string;
  rating: number;
  desc: string;
  year: string;
  duration: string;
  language: string;
  director: string;
  cast: string[];
  releaseDate: string;
  studio: string;
  poster: string;
}

export const MOVIES: Movie[] = [
  {
    id: "pathaan",
    title: "Pathaan",
    genre: "Action",
    rating: 8.2,
    desc: "A spy thriller with breathtaking action sequences across the globe. Pathaan, an exiled spy, must stop a terrorist organisation armed with a biological weapon.",
    year: "2023",
    duration: "2h 26m",
    language: "Hindi",
    director: "Siddharth Anand",
    cast: ["Shah Rukh Khan", "Deepika Padukone", "John Abraham", "Dimple Kapadia"],
    releaseDate: "25 January 2023",
    studio: "Yash Raj Films",
    poster: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600&q=80",
  },
  {
    id: "3-idiots",
    title: "3 Idiots",
    genre: "Comedy/Drama",
    rating: 9.1,
    desc: "An iconic story of friendship, dreams and the broken education system. Three engineering students challenge the conventional ways of their college.",
    year: "2009",
    duration: "2h 50m",
    language: "Hindi",
    director: "Rajkumar Hirani",
    cast: ["Aamir Khan", "R. Madhavan", "Sharman Joshi", "Kareena Kapoor", "Boman Irani"],
    releaseDate: "25 December 2009",
    studio: "Vinod Chopra Films",
    poster: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600&q=80",
  },
  {
    id: "k3g",
    title: "Kabhi Khushi Kabhie Gham",
    genre: "Drama",
    rating: 8.0,
    desc: "A family epic spanning generations, love, pride and sacrifice. Rahul returns to reunite his estranged family.",
    year: "2001",
    duration: "3h 30m",
    language: "Hindi",
    director: "Karan Johar",
    cast: ["Amitabh Bachchan", "Jaya Bachchan", "Shah Rukh Khan", "Kajol", "Hrithik Roshan", "Kareena Kapoor"],
    releaseDate: "14 December 2001",
    studio: "Dharma Productions",
    poster: "https://images.unsplash.com/photo-1512070679279-8988d32161be?w=600&q=80",
  },
  {
    id: "rrr",
    title: "RRR",
    genre: "Epic Action",
    rating: 8.7,
    desc: "An epic fictional tale about two Indian revolutionaries — Alluri Sitarama Raju and Komaram Bheem — fighting against the British colonial rule.",
    year: "2022",
    duration: "3h 7m",
    language: "Telugu",
    director: "S. S. Rajamouli",
    cast: ["N. T. Rama Rao Jr.", "Ram Charan", "Ajay Devgn", "Alia Bhatt", "Olivia Morris"],
    releaseDate: "25 March 2022",
    studio: "DVV Entertainment",
    poster: "https://images.unsplash.com/photo-1574267432553-4b4628081c31?w=600&q=80",
  },
  {
    id: "loot",
    title: "Loot",
    genre: "Nepali Thriller",
    rating: 8.5,
    desc: "Iconic Nepali heist thriller about five strangers who plan a bank robbery. It redefined Nepali cinema and became a cultural phenomenon.",
    year: "2012",
    duration: "2h 10m",
    language: "Nepali",
    director: "Nischal Basnet",
    cast: ["Saugat Malla", "Dayahang Rai", "Sushil Shrestha", "Bijay Baral", "Rishma Gurung"],
    releaseDate: "11 May 2012",
    studio: "Filmy Duniya",
    poster: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=600&q=80",
  },
  {
    id: "kabaddi",
    title: "Kabaddi",
    genre: "Nepali Comedy",
    rating: 8.1,
    desc: "Heartwarming Nepali village comedy about love and tradition. A man caught between two women navigates village life with hilarious results.",
    year: "2013",
    duration: "2h 5m",
    language: "Nepali",
    director: "Ram Babu Gurung",
    cast: ["Dayahang Rai", "Benisha Hamal", "Khagendra Lamichhane", "Karma"],
    releaseDate: "10 October 2013",
    studio: "Dristi Entertainment",
    poster: "https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?w=600&q=80",
  },
  {
    id: "dangal",
    title: "Dangal",
    genre: "Biography",
    rating: 8.4,
    desc: "Based on the true story of Mahavir Singh Phogat who trains his daughters Geeta and Babita to become world-class wrestlers.",
    year: "2016",
    duration: "2h 41m",
    language: "Hindi",
    director: "Nitesh Tiwari",
    cast: ["Aamir Khan", "Fatima Sana Shaikh", "Sanya Malhotra", "Sakshi Tanwar"],
    releaseDate: "23 December 2016",
    studio: "Walt Disney Pictures India",
    poster: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=600&q=80",
  },
  {
    id: "kgf2",
    title: "KGF Chapter 2",
    genre: "Action",
    rating: 8.2,
    desc: "Rocky's fearsome reputation spreads across the nation. As he becomes the most powerful man in the world, enemies rise from all corners.",
    year: "2022",
    duration: "2h 48m",
    language: "Kannada",
    director: "Prashanth Neel",
    cast: ["Yash", "Sanjay Dutt", "Raveena Tandon", "Srinidhi Shetty", "Prakash Raj"],
    releaseDate: "14 April 2022",
    studio: "Hombale Films",
    poster: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=600&q=80",
  },
  {
    id: "baahubali2",
    title: "Baahubali 2",
    genre: "Epic Action",
    rating: 8.5,
    desc: "The conclusion to the epic saga of power, betrayal and undying love. The mystery of why Kattappa killed Baahubali is finally revealed.",
    year: "2017",
    duration: "2h 47m",
    language: "Telugu",
    director: "S. S. Rajamouli",
    cast: ["Prabhas", "Rana Daggubati", "Anushka Shetty", "Tamannaah", "Ramya Krishnan"],
    releaseDate: "28 April 2017",
    studio: "Arka Media Works",
    poster: "https://images.unsplash.com/photo-1518929458119-e5bf444c30f4?w=600&q=80",
  },
  {
    id: "pashupati-prasad",
    title: "Pashupati Prasad",
    genre: "Nepali Drama",
    rating: 8.3,
    desc: "A moving story of hope, dignity and humanity. A janitor in Kathmandu dreams of a better life for his family.",
    year: "2016",
    duration: "2h 15m",
    language: "Nepali",
    director: "Dipen Rayamajhi",
    cast: ["Khagendra Lamichhane", "Reecha Sharma", "Buddhi Tamang", "Menuka Pradhan"],
    releaseDate: "19 February 2016",
    studio: "Himal Chuli Films",
    poster: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=600&q=80",
  },
];
