/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as HelpRouteImport } from './routes/help'
import { Route as EntertainmentRouteImport } from './routes/entertainment'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchVideoIdRouteImport } from './routes/watch.$videoId'
import { Route as PaymentContentIdRouteImport } from './routes/payment.$contentId'
import { Route as NotesNoteIdRouteImport } from './routes/notes.$noteId'
import { Route as EntertainmentMovieIdRouteImport } from './routes/entertainment.$movieId'

const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const EntertainmentRoute = EntertainmentRouteImport.update({
  id: '/entertainment',
  path: '/entertainment',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchVideoIdRoute = WatchVideoIdRouteImport.update({
  id: '/watch/$videoId',
  path: '/watch/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentContentIdRoute = PaymentContentIdRouteImport.update({
  id: '/payment/$contentId',
  path: '/payment/$contentId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => NotesRoute,
} as any)
const EntertainmentMovieIdRoute = EntertainmentMovieIdRouteImport.update({
  id: '/$movieId',
  path: '/$movieId',
  getParentRoute: () => EntertainmentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/entertainment': typeof EntertainmentRouteWithChildren
  '/help': typeof HelpRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sports': typeof SportsRoute
  '/entertainment/$movieId': typeof EntertainmentMovieIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/payment/$contentId': typeof PaymentContentIdRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/entertainment': typeof EntertainmentRouteWithChildren
  '/help': typeof HelpRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sports': typeof SportsRoute
  '/entertainment/$movieId': typeof EntertainmentMovieIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/payment/$contentId': typeof PaymentContentIdRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/entertainment': typeof EntertainmentRouteWithChildren
  '/help': typeof HelpRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sports': typeof SportsRoute
  '/entertainment/$movieId': typeof EntertainmentMovieIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/payment/$contentId': typeof PaymentContentIdRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/courses'
    | '/entertainment'
    | '/help'
    | '/learn'
    | '/login'
    | '/notes'
    | '/profile'
    | '/signup'
    | '/sports'
    | '/entertainment/$movieId'
    | '/notes/$noteId'
    | '/payment/$contentId'
    | '/watch/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/courses'
    | '/entertainment'
    | '/help'
    | '/learn'
    | '/login'
    | '/notes'
    | '/profile'
    | '/signup'
    | '/sports'
    | '/entertainment/$movieId'
    | '/notes/$noteId'
    | '/payment/$contentId'
    | '/watch/$videoId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/courses'
    | '/entertainment'
    | '/help'
    | '/learn'
    | '/login'
    | '/notes'
    | '/profile'
    | '/signup'
    | '/sports'
    | '/entertainment/$movieId'
    | '/notes/$noteId'
    | '/payment/$contentId'
    | '/watch/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  EntertainmentRoute: typeof EntertainmentRouteWithChildren
  HelpRoute: typeof HelpRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  SportsRoute: typeof SportsRoute
  PaymentContentIdRoute: typeof PaymentContentIdRoute
  WatchVideoIdRoute: typeof WatchVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entertainment': {
      id: '/entertainment'
      path: '/entertainment'
      fullPath: '/entertainment'
      preLoaderRoute: typeof EntertainmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$videoId': {
      id: '/watch/$videoId'
      path: '/watch/$videoId'
      fullPath: '/watch/$videoId'
      preLoaderRoute: typeof WatchVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$contentId': {
      id: '/payment/$contentId'
      path: '/payment/$contentId'
      fullPath: '/payment/$contentId'
      preLoaderRoute: typeof PaymentContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof NotesRoute
    }
    '/entertainment/$movieId': {
      id: '/entertainment/$movieId'
      path: '/$movieId'
      fullPath: '/entertainment/$movieId'
      preLoaderRoute: typeof EntertainmentMovieIdRouteImport
      parentRoute: typeof EntertainmentRoute
    }
  }
}

interface EntertainmentRouteChildren {
  EntertainmentMovieIdRoute: typeof EntertainmentMovieIdRoute
}

const EntertainmentRouteChildren: EntertainmentRouteChildren = {
  EntertainmentMovieIdRoute: EntertainmentMovieIdRoute,
}

const EntertainmentRouteWithChildren = EntertainmentRoute._addFileChildren(
  EntertainmentRouteChildren,
)

interface NotesRouteChildren {
  NotesNoteIdRoute: typeof NotesNoteIdRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesNoteIdRoute: NotesNoteIdRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  EntertainmentRoute: EntertainmentRouteWithChildren,
  HelpRoute: HelpRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  SportsRoute: SportsRoute,
  PaymentContentIdRoute: PaymentContentIdRoute,
  WatchVideoIdRoute: WatchVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
